export default {
  namespaced: true,
  state: {
    ii: 0, // items array index
    editMode: false,
    epiInflectionalCharImgRight: require("@/assets/morfologi/epi_inflectional/rev.png"),
    epiInflectionalCharImgLeft: require("@/assets/morfologi/epi_inflectional/elg.png"),
    items: [
      {
        id: 0,
        type: "EpiInflectional",
        isPractice: true,
        feedbackCorrect: require("@/assets/morfologi/epi_inflectional/feedback1_correct.mp3"),
        feedbackWrong: require("@/assets/morfologi/epi_inflectional/feedback1_wrong.mp3"),
        isInstruction: true,
        instructionAudio: require("@/assets/morfologi/epi_inflectional/instructionAudio.mp3"),
        img: require("@/assets/morfologi/epi_inflectional/example1.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/example1_right.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/example1_left.mp3"),
        sentenceRight: "Skilpadden leker med en duss ",
        sentenceLeft: "Skilpadden leker med tre dusser ",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 1,
        type: "EpiInflectional",
        isPractice: true,
        feedbackCorrect: require("@/assets/morfologi/epi_inflectional/feedback2_correct.mp3"),
        feedbackWrong: require("@/assets/morfologi/epi_inflectional/feedback2_wrong.mp3"),
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/example2.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/example2_right.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/example2_left.mp3"),
        sentenceRight: "Skilpadden ser en føls klovn. ",
        sentenceLeft: "Skilpadden ser følse klovner.",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 2,
        type: "EpiInflectional",
        isPractice: true,
        feedbackCorrect: require("@/assets/morfologi/epi_inflectional/feedback3_correct.mp3"),
        feedbackWrong: require("@/assets/morfologi/epi_inflectional/feedback3_wrong.mp3"),
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/example3.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/example3_right.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/example3_left.mp3"),
        sentenceRight: "I går vukket skilpadden et hus",
        sentenceLeft: "Nå vukker skilpadden et hus",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 3,
        type: "EpiInflectional",
        isPractice: true,
        feedbackCorrect: require("@/assets/morfologi/epi_inflectional/feedback4_correct.mp3"),
        feedbackWrong: require("@/assets/morfologi/epi_inflectional/feedback4_wrong.mp3"),
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/example4.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/example4_right.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/example4_left.mp3"),
        sentenceRight: "Nå gjummer skilpadden tørsten med vann",
        sentenceLeft: "I går gjumte skilpadden tørsten med vann",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 4,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item1.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/1r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/1l.mp3"),
        sentenceRight: "Skilpadden hilser på ådene",
        sentenceLeft: "Skilpadden hilser på åden",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 5,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item2.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/2r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/2l.mp3"),
        sentenceRight: "Skilpaddene går ombord i jægen",
        sentenceLeft: "Skilpaddene går ombord i jægene",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 6,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item3.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/3r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/3l.mp3"),
        sentenceRight: "Skilpadden bærer favene",
        sentenceLeft: "Skilpadden bærer faven",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 7,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item4.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/4r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/4l.mp3"),
        sentenceRight: "Skilpadden holder en væsp",
        sentenceLeft: "Skilpadden holder to væsper",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 8,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item5.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/5r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/5l.mp3"),
        sentenceRight: "Skilpadden fargelegger åmtet",
        sentenceLeft: "Skilpadden fargelegger åmtene",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 9,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item6.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/6r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/6l.mp3"),
        sentenceRight: "Skilpadden spretter kebelen",
        sentenceLeft: "Skilpadden spretter keblene",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 10,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item7.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/7r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/7l.mp3"),
        sentenceRight: "Skilpadden sklir ned de prosse sklien",
        sentenceLeft: "Skilpadden sklir ned den prosse skli",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 11,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item8.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/8r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/8l.mp3"),
        sentenceRight: "Skilpadden spiser en prin sitro",
        sentenceLeft: "Skilpadden spiser prine sitrone",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 12,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item9.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/9r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/9l.mp3"),
        sentenceRight: "Skilpadden ligger på en kræs pute.",
        sentenceLeft: "Skilpadden ligger på kræse puter",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 13,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item10.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/10r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/10l.mp3"),
        sentenceRight: "Skilpadden drikker av en flei kopp ",
        sentenceLeft: "Skilpadden drikker av fleie kopper",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 14,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item11.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/11r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/11l.mp3"),
        sentenceRight: "Skilpadden kaster de kvyre skoene",
        sentenceLeft: "Skilpadden kaster den kvyre skoe",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 15,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item12.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/12r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/12l.mp3"),
        sentenceRight: "Nå pyrer skilpaddene i mål.",
        sentenceLeft: "I går pyrte skilpaddene i mål",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 16,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item13.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/13r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/13l.mp3"),
        sentenceRight: "Nå såmerer skilpadden en pakk",
        sentenceLeft: "I går såmerte skilpadden en pakk",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 17,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item14.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/14r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/14l.mp3"),
        sentenceRight: "I går terdret skilpadden på butikken",
        sentenceLeft: "Nå terdrer skilpadden på butikken.",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 18,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item15.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/15r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/15l.mp3"),
        sentenceRight: "Nå gudder skilpadden sakte.",
        sentenceLeft: "I går guddet skilpadden sakte. ",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 19,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item16.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/16r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/16l.mp3"),
        sentenceRight: "I går kræste skilpaddene sammen",
        sentenceLeft: "Nå kræser skilpaddene sammen.",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 20,
        type: "MetaInflectional",
        isInstruction: true,
        instructionAudio: require("@/assets/morfologi/meta_inflectional/instructionAudio.mp3"),
        isPractice: true,
        feedbackCorrect: require("@/assets/morfologi/meta_inflectional/feedback1_correct.mp3"),
        feedbackWrong: require("@/assets/morfologi/meta_inflectional/feedback1_wrong.mp3"),
        imgLeft: require("@/assets/morfologi/meta_inflectional/example1L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/example1R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/example1_right.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/example1_left.mp3"),
        sentenceLeft: "Skilpadden leker med en duss",
        sentenceRight: "Skilpadden leker med tre..",
        answerKey: "dusser",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 21,
        type: "MetaInflectional",
        isInstruction: false,
        instructionAudio: null,
        isPractice: true,
        feedbackCorrect: require("@/assets/morfologi/meta_inflectional/feedback2_correct.mp3"),
        feedbackWrong: require("@/assets/morfologi/meta_inflectional/feedback2_wrong.mp3"),
        imgLeft: require("@/assets/morfologi/meta_inflectional/example2L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/example2R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/example2_right.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/example2_left.mp3"),
        sentenceLeft: "Skilpadden ser en føls klovn",
        sentenceRight: "Skilpadden ser..",
        answerKey: "følse klovner",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 22,
        type: "MetaInflectional",
        isInstruction: false,
        instructionAudio: null,
        isPractice: true,
        feedbackCorrect: require("@/assets/morfologi/meta_inflectional/feedback3_correct.mp3"),
        feedbackWrong: require("@/assets/morfologi/meta_inflectional/feedback3_wrong.mp3"),
        imgLeft: require("@/assets/morfologi/meta_inflectional/example3L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/example3R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/example3_right.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/example3_left.mp3"),
        sentenceLeft: "I går vukket skilpadden et hus",
        sentenceRight: "Nå..",
        answerKey: "vukker skilpadden et hus",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 23,
        type: "MetaInflectional",
        isInstruction: false,
        instructionAudio: null,
        isPractice: true,
        feedbackCorrect: require("@/assets/morfologi/meta_inflectional/feedback4_correct.mp3"),
        feedbackWrong: require("@/assets/morfologi/meta_inflectional/feedback4_wrong.mp3"),
        imgLeft: require("@/assets/morfologi/meta_inflectional/example4L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/example4R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/example4_right.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/example4_left.mp3"),
        sentenceLeft: "Nå gjummer skilpadden tørsten med vann",
        sentenceRight: "I går..",
        answerKey: "gjumte skilpadden tørsten med vann",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 24,
        type: "MetaInflectional",
        isInstruction: false,
        instructionAudio: null,
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item1L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item1R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/1r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/1l.mp3"),
        sentenceLeft: "Skilpadden hilser på ådene",
        sentenceRight: "Skilpadden hilser på..",
        answerKey: "åden ",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 25,
        type: "MetaInflectional",
        isInstruction: false,
        instructionAudio: null,
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item2L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item2R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/2r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/2l.mp3"),
        sentenceLeft: "Skilpaddene går ombord i jægen",
        sentenceRight: "Skilpaddene går ombord i..",
        answerKey: "jægene ",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 26,
        type: "MetaInflectional",
        isInstruction: false,
        instructionAudio: null,
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item3L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item3R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/3r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/3l.mp3"),
        sentenceLeft: "Skilpadden bærer favene",
        sentenceRight: "Skilpadden bærer..",
        answerKey: "faven ",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 27,
        type: "MetaInflectional",
        isInstruction: false,
        instructionAudio: null,
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item4L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item4R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/4r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/4l.mp3"),
        sentenceLeft: "Skilpadden holder en væsp",
        sentenceRight: "Skilpadden holder to..",
        answerKey: "væsper ",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 28,
        type: "MetaInflectional",
        isInstruction: false,
        instructionAudio: null,
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item5L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item5R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/5r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/5l.mp3"),
        sentenceLeft: "Skilpadden fargelegger åmtet",
        sentenceRight: "Skilpadden fargelegger..",
        answerKey: "åmtene ",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 29,
        type: "MetaInflectional",
        isInstruction: false,
        instructionAudio: null,
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item6L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item6R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/6r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/6l.mp3"),
        sentenceLeft: "Skilpadden spretter kebelen",
        sentenceRight: "Skilpadden spretter..",
        answerKey: "keblene ",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 30,
        type: "MetaInflectional",
        isInstruction: false,
        instructionAudio: null,
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item7L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item7R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/7r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/7l.mp3"),
        sentenceLeft: "Skilpadden sklir ned de prosse skliene",
        sentenceRight: "Skilpadden sklir ned den..",
        answerKey: "prosse sklia (begge ordene for poeng)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 31,
        type: "MetaInflectional",
        isInstruction: false,
        instructionAudio: null,
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item8L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item8R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/8r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/8l.mp3"),
        sentenceLeft: "Skilpadden spiser en prin sitron",
        sentenceRight: "Skilpadden spiser..",
        answerKey: "prine sitroner (begge ordene)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 32,
        type: "MetaInflectional",
        isInstruction: false,
        instructionAudio: null,
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item9L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item9R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/9r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/9l.mp3"),
        sentenceLeft: "Skilpadden ligger på en kræs pute",
        sentenceRight: "Skilpadden ligger på..",
        answerKey: "kræse puter (begge ordene)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 33,
        type: "MetaInflectional",
        isInstruction: false,
        instructionAudio: null,
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item10L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item10R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/10r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/10l.mp3"),
        sentenceLeft: "Skilpadden drikker av en flei kopp",
        sentenceRight: "Skilpadden drikker av..",
        answerKey: "fleie kopper (begge ordene)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 34,
        type: "MetaInflectional",
        isInstruction: false,
        instructionAudio: null,
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item11L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item11R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/11r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/11l.mp3"),
        sentenceLeft: "Skilpadden kaster de kvyre skoene",
        sentenceRight: "Skilpadden kaster den..",
        answerKey: "kvyre skoen (begge ordene)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 35,
        type: "MetaInflectional",
        isInstruction: false,
        instructionAudio: null,
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item12L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item12R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/12r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/12l.mp3"),
        sentenceLeft: "Nå pyrer skilpaddene i mål",
        sentenceRight: "I går..",
        answerKey: "pyrte skilpaddene i mål",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 36,
        type: "MetaInflectional",
        isInstruction: false,
        instructionAudio: null,
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item13L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item13R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/13r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/13l.mp3"),
        sentenceLeft: "Nå såmerer skilpadden en pakke",
        sentenceRight: "I går..",
        answerKey: "såmerte skilpadden en pakke",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 37,
        type: "MetaInflectional",
        isInstruction: false,
        instructionAudio: null,
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item14L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item14R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/14r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/14l.mp3"),
        sentenceLeft: "I går terdret skilpadden på butikken",
        sentenceRight: "Nå..",
        answerKey: "terdrer skilpadden på butikken",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 38,
        type: "MetaInflectional",
        isInstruction: false,
        instructionAudio: null,
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item15L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item15R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/15r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/15l.mp3"),
        sentenceLeft: "Nå gudder skilpadden sakte",
        sentenceRight: "I går..",
        answerKey: "guddet skilpadden sakte",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 39,
        type: "MetaInflectional",
        isInstruction: false,
        instructionAudio: null,
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item16L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item16R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/16r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/16l.mp3"),
        sentenceLeft: "I går kræste skilpaddene sammen",
        sentenceRight: "Nå..",
        answerKey: "kræser skilpaddene sammen",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
    ],
  },
  getters: {},
  mutations: {
    incrementII(state) {
      state.ii++;
    },
    decrementII(state) {
      state.ii--;
    },
    setII(state, n: number) {
      state.ii = n;
    },
    recordAnswer(state, payload) {
      state.items[state.ii].userAnswer = payload.userAnswer;
    },
    toggleEditMode(state) {
      state.editMode = !state.editMode;
    },
  },
  actions: {
    playAudio: ({ commit, state }, payload) => {
      //Currently not used
      console.log(commit, state, payload); //To supress linting warnings of unused variables
    },
  },
  modules: {},
};
