export default {
  namespaced: true,
  state: {
    ii: 0, // items array index
    editMode: true,
    items: [
      {
        id: 0,
        type: "TestScreen",
        isPractice: true,
        feedbackCorrect: require("@/assets/morfologi/epi_inflectional/feedback1_correct.mp3"),
        feedbackWrong: require("@/assets/morfologi/epi_inflectional/feedback1_wrong.mp3"),
        isInstruction: true,
        instructionAudio: require("@/assets/morfologi/epi_inflectional/instructionAudio.mp3"),
        img: require("@/assets/morfologi/epi_inflectional/example1.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/example1_right.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/example1_left.mp3"),
        sentenceRight: "Skilpadden leker med en duss ",
        sentenceLeft: "ORDFORRAAD ",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 1,
        type: "EpiInflectional",
        isPractice: true,
        feedbackCorrect: require("@/assets/morfologi/epi_inflectional/feedback2_correct.mp3"),
        feedbackWrong: require("@/assets/morfologi/epi_inflectional/feedback2_wrong.mp3"),
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/example2.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/example2_right.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/example2_left.mp3"),
        sentenceRight: "Skilpadden ser en føls klovn. ",
        sentenceLeft: "Skilpadden ser følse klovner.",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 2,
        type: "TestScreen",
        isPractice: true,
        feedbackCorrect: require("@/assets/morfologi/epi_inflectional/feedback3_correct.mp3"),
        feedbackWrong: require("@/assets/morfologi/epi_inflectional/feedback3_wrong.mp3"),
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/example3.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/example3_right.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/example3_left.mp3"),
        sentenceRight: "I går vukket skilpadden et hus",
        sentenceLeft: "Nå vukker skilpadden et hus",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 3,
        type: "TestScreen",
        isPractice: true,
        feedbackCorrect: require("@/assets/morfologi/epi_inflectional/feedback4_correct.mp3"),
        feedbackWrong: require("@/assets/morfologi/epi_inflectional/feedback4_wrong.mp3"),
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/example4.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/example4_right.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/example4_left.mp3"),
        sentenceRight: "Nå gjummer skilpadden tørsten med vann",
        sentenceLeft: "I går gjumte skilpadden tørsten med vann",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 4,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item1.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/1r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/1l.mp3"),
        sentenceRight: "Skilpadden hilser på ådene",
        sentenceLeft: "Skilpadden hilser på åden",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 5,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item2.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/2r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/2l.mp3"),
        sentenceRight: "Skilpaddene går ombord i jægen",
        sentenceLeft: "Skilpaddene går ombord i jægene",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 6,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item3.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/3r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/3l.mp3"),
        sentenceRight: "Skilpadden bærer favene",
        sentenceLeft: "Skilpadden bærer faven",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 7,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item4.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/4r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/4l.mp3"),
        sentenceRight: "Skilpadden holder en væsp",
        sentenceLeft: "Skilpadden holder to væsper",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 8,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item5.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/5r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/5l.mp3"),
        sentenceRight: "Skilpadden fargelegger åmtet",
        sentenceLeft: "Skilpadden fargelegger åmtene",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 9,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item6.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/6r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/6l.mp3"),
        sentenceRight: "Skilpadden spretter kebelen",
        sentenceLeft: "Skilpadden spretter keblene",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 10,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item7.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/7r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/7l.mp3"),
        sentenceRight: "Skilpadden sklir ned de prosse sklien",
        sentenceLeft: "Skilpadden sklir ned den prosse skli",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 11,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item8.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/8r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/8l.mp3"),
        sentenceRight: "Skilpadden spiser en prin sitro",
        sentenceLeft: "Skilpadden spiser prine sitrone",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 12,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item9.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/9r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/9l.mp3"),
        sentenceRight: "Skilpadden ligger på en kræs pute.",
        sentenceLeft: "Skilpadden ligger på kræse puter",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 13,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item10.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/10r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/10l.mp3"),
        sentenceRight: "Skilpadden drikker av en flei kopp ",
        sentenceLeft: "Skilpadden drikker av fleie kopper",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 14,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item11.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/11r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/11l.mp3"),
        sentenceRight: "Skilpadden kaster de kvyre skoene",
        sentenceLeft: "Skilpadden kaster den kvyre skoe",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 15,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item12.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/12r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/12l.mp3"),
        sentenceRight: "Nå pyrer skilpaddene i mål.",
        sentenceLeft: "I går pyrte skilpaddene i mål",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 16,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item13.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/13r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/13l.mp3"),
        sentenceRight: "Nå såmerer skilpadden en pakk",
        sentenceLeft: "I går såmerte skilpadden en pakk",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 17,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item14.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/14r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/14l.mp3"),
        sentenceRight: "I går terdret skilpadden på butikken",
        sentenceLeft: "Nå terdrer skilpadden på butikken.",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 18,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item15.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/15r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/15l.mp3"),
        sentenceRight: "Nå gudder skilpadden sakte.",
        sentenceLeft: "I går guddet skilpadden sakte. ",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 19,
        type: "EpiInflectional",
        isPractice: false,
        feedbackCorrect: null,
        feedbackWrong: null,
        isInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item16.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/16r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/16l.mp3"),
        sentenceRight: "I går kræste skilpaddene sammen",
        sentenceLeft: "Nå kræser skilpaddene sammen.",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 0,
        type: "Screen1",
        question: "Hvem er Randy?",
        answer: "Venstre",
        imgLeft: require("@/assets/left.jpg"),
        imgRight: require("@/assets/right.jpg"),
        userAnswer: null,
      },
      {
        id: 1,
        type: "Screen1",
        question: "Hvem er president i USA?",
        answer: "Donald Trump",
        imgLeft: require("@/assets/1l.png"),
        imgRight: require("@/assets/1r.png"),
        userAnswer: null,
      },
      {
        id: 2,
        type: "Screen2",
        question: "Hvem er ordfører i Andeby?",
        answer: "Bavian Slang",
        imgLeft: require("@/assets/2l.png"),
        imgRight: require("@/assets/2r.png"),
        userAnswer: null,
      },
      {
        id: 3,
        type: "Screen2",
        imgLeft: require("@/assets/3l.png"),
        imgRight: require("@/assets/3r.png"),
        userAnswer: null,
      },
    ],
  },
  getters: {
    items: (state) => state.items,
    ii: (state) => state.ii,
    editMode: (state) => state.editMode,
  },
  mutations: {
    incrementII(state) {
      state.ii++;
    },
    decrementII(state) {
      state.ii--;
    },
    setII(state, n: number) {
      state.ii = n;
    },
    recordAnswer(state, payload) {
      state.items[state.ii].userAnswer = payload.userAnswer;
    },
    toggleEditMode(state) {
      state.editMode = !state.editMode;
    },
  },
  actions: {
    playAudio: ({ commit, state }, payload) => {
      //Currently not used
      console.log(commit, state, payload); //To supress linting warnings of unused variables
    },
  },
  modules: {},
};
