export default {
  namespaced: true,
  state: {
    ii: 0, // screens array index
    editMode: false,
    screens: [
      {
        id: -3,
        type: "ExaminerInstructions",
        orientation: "landscape",
        isPractice: false,
        isScored: false,
        isNarratorInstruction: false,
        heading: "Tallforståelse: Instruksjoner til eksaminator",
        body: `Tallforståelse

Før du begynner: Du må skrive ut 4 ark for å bruke denne testen. 
        
Dokumentet du må skrive ut kan lastes ned lenken under. 
(for eksempel på en PC tilkoblet skriver):

http://link-til-utskrift.eksempel

Instruksjoner for gjennomføring av denne testen er som følger: bla bla bla...
    `,
      },

      {
        id: -2,
        type: "ParticipantRegistration",
        orientation: "landscape",
        isPractice: false,
        isScored: false,
        isNarratorInstruction: false,
        heading: "Registrer forsøksdeltaker",
        body: `Generelt:
      Dato for testing:
      Eksaminator navn:
      Kommentarer og notater:
      Deltaker:
      ID:
      Navn:
      Fødselsdato:
      Test-gruppe:
      Skole:
      Klassetrinn:
      • Førskole
      • 1. klasse
      • 2. klasse
      • 3. klasse
      Kjønn:
      • Gutt
      • Jente
      • Annet
      `,
      },
      {
        id: -1,
        type: "ParticipantIntroduction",
        orientation: "landscape",
        heading: "Introduksjon",
        isPractice: false,
        isScored: false,
        instructionAudio: require("@/assets/morfologi/introductionAudio.mp3"),
      },

      {
        id: 0,
        orientation: "landscape",
        type: "ReadingNumbers",
        isPractice: true,
        isScored: false,
        isNarratorInstruction: true,
        instructionAudio: require("@/assets/tallforstaaelse/number_reading/stimulus-audio-prompt.mp3"),
        numberStimulus: 9,
        audioRight: require("@/assets/morfologi/epi_inflectional/example1_right.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/example1_left.mp3"),
        sentenceRight: "Skilpadden leker med en duss ",
        sentenceLeft: "Skilpadden leker med tre dusser ",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 1,
        orientation: "landscape",
        type: "NumberRecognition",
        isPractice: true,
        isScored: false,
        isNarratorInstruction: true,
        instructionAudio: require("@/assets/tallforstaaelse/number_recognition/stimulus-audio-prompt.mp3"),
        img: require("@/assets/morfologi/epi_inflectional/example2.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/example2_right.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/example2_left.mp3"),
        sentenceRight: "Skilpadden ser en føls klovn. ",
        sentenceLeft: "Skilpadden ser følse klovner.",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 2,
        orientation: "landscape",
        type: "DigitComparision",
        isPractice: true,
        isScored: false,
        isNarratorInstruction: true,
        instructionAudio: require("@/assets/tallforstaaelse/digit_comparision/stimulus-audio-prompt.mp3"),
        img: require("@/assets/morfologi/epi_inflectional/example3.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/example3_right.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/example3_left.mp3"),
        sentenceRight: "I går vukket skilpadden et hus",
        sentenceLeft: "Nå vukker skilpadden et hus",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 3,
        orientation: "landscape",
        type: "DotsToDigits",
        isPractice: true,
        isScored: false,
        isNarratorInstruction: true,
        instructionAudio: require("@/assets/tallforstaaelse/dots_to_digits/stimulus-audio-prompt.mp3"),
        img: require("@/assets/tallforstaaelse/dots_to_digits/eksempel.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/example4_right.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/example4_left.mp3"),
        sentenceRight: "Nå gjummer skilpadden tørsten med vann",
        sentenceLeft: "I går gjumte skilpadden tørsten med vann",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 4,
        orientation: "landscape",
        type: "ArithmeticOral",
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        isNarratorInstruction: true,
        instructionAudio: require("@/assets/tallforstaaelse/arithmetic_oral/stimulus-audio-prompt.mp3"),
        img: require("@/assets/morfologi/epi_inflectional/item1.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/1r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/1l.mp3"),
        sentenceRight: "Skilpadden hilser på ådene",
        sentenceLeft: "Skilpadden hilser på åden",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 5,
        orientation: "landscape",
        type: "ArithmeticWritten",
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        isNarratorInstruction: true,
        instructionAudio: null,
        img: require("@/assets/tallforstaaelse/arithmetic_written/eksempel.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/2r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/2l.mp3"),
        sentenceRight: "Skilpaddene går ombord i jægen",
        sentenceLeft: "Skilpaddene går ombord i jægene",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 6,
        orientation: "landscape",
        type: "EpiInflectional",
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        isNarratorInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item3.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/3r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/3l.mp3"),
        sentenceRight: "Skilpadden bærer favene",
        sentenceLeft: "Skilpadden bærer faven",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 7,
        orientation: "landscape",
        type: "EpiInflectional",
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        isNarratorInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item4.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/4r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/4l.mp3"),
        sentenceRight: "Skilpadden holder en væsp",
        sentenceLeft: "Skilpadden holder to væsper",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 8,
        orientation: "landscape",
        type: "EpiInflectional",
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        isNarratorInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item5.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/5r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/5l.mp3"),
        sentenceRight: "Skilpadden fargelegger åmtet",
        sentenceLeft: "Skilpadden fargelegger åmtene",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 9,
        orientation: "landscape",
        type: "EpiInflectional",
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        isNarratorInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item6.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/6r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/6l.mp3"),
        sentenceRight: "Skilpadden spretter kebelen",
        sentenceLeft: "Skilpadden spretter keblene",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 10,
        orientation: "landscape",
        type: "EpiInflectional",
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        isNarratorInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item7.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/7r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/7l.mp3"),
        sentenceRight: "Skilpadden sklir ned de prosse sklien",
        sentenceLeft: "Skilpadden sklir ned den prosse skli",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 11,
        orientation: "landscape",
        type: "EpiInflectional",
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        isNarratorInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item8.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/8r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/8l.mp3"),
        sentenceRight: "Skilpadden spiser en prin sitro",
        sentenceLeft: "Skilpadden spiser prine sitrone",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 12,
        orientation: "landscape",
        type: "EpiInflectional",
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        isNarratorInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item9.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/9r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/9l.mp3"),
        sentenceRight: "Skilpadden ligger på en kræs pute.",
        sentenceLeft: "Skilpadden ligger på kræse puter",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 13,
        orientation: "landscape",
        type: "EpiInflectional",
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        isNarratorInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item10.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/10r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/10l.mp3"),
        sentenceRight: "Skilpadden drikker av en flei kopp ",
        sentenceLeft: "Skilpadden drikker av fleie kopper",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 14,
        orientation: "landscape",
        type: "EpiInflectional",
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        isNarratorInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item11.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/11r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/11l.mp3"),
        sentenceRight: "Skilpadden kaster de kvyre skoene",
        sentenceLeft: "Skilpadden kaster den kvyre skoe",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 15,
        orientation: "landscape",
        type: "EpiInflectional",
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        isNarratorInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item12.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/12r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/12l.mp3"),
        sentenceRight: "Nå pyrer skilpaddene i mål.",
        sentenceLeft: "I går pyrte skilpaddene i mål",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 16,
        orientation: "landscape",
        type: "EpiInflectional",
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        isNarratorInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item13.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/13r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/13l.mp3"),
        sentenceRight: "Nå såmerer skilpadden en pakk",
        sentenceLeft: "I går såmerte skilpadden en pakk",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 17,
        orientation: "landscape",
        type: "EpiInflectional",
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        isNarratorInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item14.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/14r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/14l.mp3"),
        sentenceRight: "I går terdret skilpadden på butikken",
        sentenceLeft: "Nå terdrer skilpadden på butikken.",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 18,
        orientation: "landscape",
        type: "EpiInflectional",
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        isNarratorInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item15.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/15r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/15l.mp3"),
        sentenceRight: "Nå gudder skilpadden sakte.",
        sentenceLeft: "I går guddet skilpadden sakte. ",
        answerKey: "right",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 19,
        orientation: "landscape",
        type: "EpiInflectional",
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        isNarratorInstruction: false,
        instructionAudio: null,
        img: require("@/assets/morfologi/epi_inflectional/item16.png"),
        audioRight: require("@/assets/morfologi/epi_inflectional/16r.mp3"),
        audioLeft: require("@/assets/morfologi/epi_inflectional/16l.mp3"),
        sentenceRight: "I går kræste skilpaddene sammen",
        sentenceLeft: "Nå kræser skilpaddene sammen.",
        answerKey: "left",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 20,
        orientation: "landscape",
        type: "MetaInflectional",
        isNarratorInstruction: true,
        instructionAudio: require("@/assets/morfologi/meta_inflectional/instructionAudio.mp3"),
        isPractice: true,
        isScored: false,
        feedbackCorrect: require("@/assets/morfologi/meta_inflectional/feedback1_correct.mp3"),
        feedbackWrong: require("@/assets/morfologi/meta_inflectional/feedback1_wrong.mp3"),
        imgLeft: require("@/assets/morfologi/meta_inflectional/example1L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/example1R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/example1_right.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/example1_left.mp3"),
        sentenceLeft: "Skilpadden leker med en duss",
        sentenceRight: "Skilpadden leker med tre..",
        answerKey: "dusser",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 21,
        orientation: "landscape",
        type: "MetaInflectional",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: true,
        isScored: false,
        feedbackCorrect: require("@/assets/morfologi/meta_inflectional/feedback2_correct.mp3"),
        feedbackWrong: require("@/assets/morfologi/meta_inflectional/feedback2_wrong.mp3"),
        imgLeft: require("@/assets/morfologi/meta_inflectional/example2L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/example2R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/example2_right.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/example2_left.mp3"),
        sentenceLeft: "Skilpadden ser en føls klovn",
        sentenceRight: "Skilpadden ser..",
        answerKey: "følse klovner",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 22,
        orientation: "landscape",
        type: "MetaInflectional",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: true,
        isScored: false,
        feedbackCorrect: require("@/assets/morfologi/meta_inflectional/feedback3_correct.mp3"),
        feedbackWrong: require("@/assets/morfologi/meta_inflectional/feedback3_wrong.mp3"),
        imgLeft: require("@/assets/morfologi/meta_inflectional/example3L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/example3R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/example3_right.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/example3_left.mp3"),
        sentenceLeft: "I går vukket skilpadden et hus",
        sentenceRight: "Nå..",
        answerKey: "vukker skilpadden et hus",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 23,
        orientation: "landscape",
        type: "MetaInflectional",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: true,
        isScored: false,
        feedbackCorrect: require("@/assets/morfologi/meta_inflectional/feedback4_correct.mp3"),
        feedbackWrong: require("@/assets/morfologi/meta_inflectional/feedback4_wrong.mp3"),
        imgLeft: require("@/assets/morfologi/meta_inflectional/example4L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/example4R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/example4_right.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/example4_left.mp3"),
        sentenceLeft: "Nå gjummer skilpadden tørsten med vann",
        sentenceRight: "I går..",
        answerKey: "gjumte skilpadden tørsten med vann",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 24,
        orientation: "landscape",
        type: "MetaInflectional",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item1L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item1R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/1r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/1l.mp3"),
        sentenceLeft: "Skilpadden hilser på ådene",
        sentenceRight: "Skilpadden hilser på..",
        answerKey: "åden ",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 25,
        orientation: "landscape",
        type: "MetaInflectional",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item2L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item2R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/2r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/2l.mp3"),
        sentenceLeft: "Skilpaddene går ombord i jægen",
        sentenceRight: "Skilpaddene går ombord i..",
        answerKey: "jægene ",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 26,
        orientation: "landscape",
        type: "MetaInflectional",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item3L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item3R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/3r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/3l.mp3"),
        sentenceLeft: "Skilpadden bærer favene",
        sentenceRight: "Skilpadden bærer..",
        answerKey: "faven ",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 27,
        orientation: "landscape",
        type: "MetaInflectional",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item4L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item4R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/4r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/4l.mp3"),
        sentenceLeft: "Skilpadden holder en væsp",
        sentenceRight: "Skilpadden holder to..",
        answerKey: "væsper ",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 28,
        orientation: "landscape",
        type: "MetaInflectional",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item5L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item5R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/5r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/5l.mp3"),
        sentenceLeft: "Skilpadden fargelegger åmtet",
        sentenceRight: "Skilpadden fargelegger..",
        answerKey: "åmtene ",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 29,
        orientation: "landscape",
        type: "MetaInflectional",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item6L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item6R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/6r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/6l.mp3"),
        sentenceLeft: "Skilpadden spretter kebelen",
        sentenceRight: "Skilpadden spretter..",
        answerKey: "keblene ",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 30,
        orientation: "landscape",
        type: "MetaInflectional",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item7L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item7R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/7r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/7l.mp3"),
        sentenceLeft: "Skilpadden sklir ned de prosse skliene",
        sentenceRight: "Skilpadden sklir ned den..",
        answerKey: "prosse sklia (begge ordene for poeng)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 31,
        orientation: "landscape",
        type: "MetaInflectional",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item8L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item8R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/8r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/8l.mp3"),
        sentenceLeft: "Skilpadden spiser en prin sitron",
        sentenceRight: "Skilpadden spiser..",
        answerKey: "prine sitroner (begge ordene)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 32,
        orientation: "landscape",
        type: "MetaInflectional",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item9L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item9R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/9r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/9l.mp3"),
        sentenceLeft: "Skilpadden ligger på en kræs pute",
        sentenceRight: "Skilpadden ligger på..",
        answerKey: "kræse puter (begge ordene)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 33,
        orientation: "landscape",
        type: "MetaInflectional",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item10L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item10R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/10r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/10l.mp3"),
        sentenceLeft: "Skilpadden drikker av en flei kopp",
        sentenceRight: "Skilpadden drikker av..",
        answerKey: "fleie kopper (begge ordene)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 34,
        orientation: "landscape",
        type: "MetaInflectional",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item11L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item11R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/11r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/11l.mp3"),
        sentenceLeft: "Skilpadden kaster de kvyre skoene",
        sentenceRight: "Skilpadden kaster den..",
        answerKey: "kvyre skoen (begge ordene)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 35,
        orientation: "landscape",
        type: "MetaInflectional",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item12L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item12R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/12r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/12l.mp3"),
        sentenceLeft: "Nå pyrer skilpaddene i mål",
        sentenceRight: "I går..",
        answerKey: "pyrte skilpaddene i mål",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 36,
        orientation: "landscape",
        type: "MetaInflectional",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item13L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item13R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/13r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/13l.mp3"),
        sentenceLeft: "Nå såmerer skilpadden en pakke",
        sentenceRight: "I går..",
        answerKey: "såmerte skilpadden en pakke",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 37,
        orientation: "landscape",
        type: "MetaInflectional",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item14L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item14R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/14r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/14l.mp3"),
        sentenceLeft: "I går terdret skilpadden på butikken",
        sentenceRight: "Nå..",
        answerKey: "terdrer skilpadden på butikken",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 38,
        orientation: "landscape",
        type: "MetaInflectional",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item15L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item15R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/15r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/15l.mp3"),
        sentenceLeft: "Nå gudder skilpadden sakte",
        sentenceRight: "I går..",
        answerKey: "guddet skilpadden sakte",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 39,
        orientation: "landscape",
        type: "MetaInflectional",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        imgLeft: require("@/assets/morfologi/meta_inflectional/item16L.png"),
        imgRight: require("@/assets/morfologi/meta_inflectional/item16R.png"),
        audioRight: require("@/assets/morfologi/meta_inflectional/16r.mp3"),
        audioLeft: require("@/assets/morfologi/meta_inflectional/16l.mp3"),
        sentenceLeft: "I går kræste skilpaddene sammen",
        sentenceRight: "Nå..",
        answerKey: "kræser skilpaddene sammen",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 40,
        type: "MetaDerivational",
        orientation: "landscape",
        isNarratorInstruction: true,
        instructionAudio: require("@/assets/morfologi/meta_derivational/instructionAudio.mp3"),
        isPractice: true,
        isScored: false,
        feedbackCorrect: require("@/assets/morfologi/meta_derivational/feedback1_correct.mp3"),
        feedbackWrong: require("@/assets/morfologi/meta_derivational/feedback1_wrong.mp3"),
        img: require("@/assets/morfologi/meta_derivational/example1.jpg"),
        audio1: require("@/assets/morfologi/meta_derivational/example1_1.mp3"),
        audio2: require("@/assets/morfologi/meta_derivational/example1_2.mp3"),
        sentence1: "Jenta tegner.",
        sentence2: "Derfor kan vi si at jenta lager en...",
        answerKey: "(tegning)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 41,
        type: "MetaDerivational",
        orientation: "landscape",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: true,
        isScored: false,
        feedbackCorrect: require("@/assets/morfologi/meta_derivational/feedback2_correct.mp3"),
        feedbackWrong: require("@/assets/morfologi/meta_derivational/feedback2_wrong.mp3"),
        img: require("@/assets/morfologi/meta_derivational/example2.jpg"),
        audio1: require("@/assets/morfologi/meta_derivational/example2_1.mp3"),
        audio2: require("@/assets/morfologi/meta_derivational/example2_2.mp3"),
        sentence1: "Lukas er glad i svømming.",
        sentence2: "Lukas er glad i å...",
        answerKey: "( svømme)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 42,
        type: "MetaDerivational",
        orientation: "landscape",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: true,
        isScored: false,
        feedbackCorrect: require("@/assets/morfologi/meta_derivational/feedback3_correct.mp3"),
        feedbackWrong: require("@/assets/morfologi/meta_derivational/feedback3_wrong.mp3"),
        img: require("@/assets/morfologi/meta_derivational/example3.jpg"),
        audio1: require("@/assets/morfologi/meta_derivational/example3_1.mp3"),
        audio2: require("@/assets/morfologi/meta_derivational/example3_2.mp3"),
        sentence1: "Hun blir forvirret av spillet.",
        sentence2: "Hun synes spillet er...",
        answerKey: "(forvirrende)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 43,
        type: "MetaDerivational",
        orientation: "landscape",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: true,
        isScored: false,
        feedbackCorrect: require("@/assets/morfologi/meta_derivational/feedback4_correct.mp3"),
        feedbackWrong: require("@/assets/morfologi/meta_derivational/feedback4_wrong.mp3"),
        img: require("@/assets/morfologi/meta_derivational/example4.jpg"),
        audio1: require("@/assets/morfologi/meta_derivational/example4_1.mp3"),
        audio2: require("@/assets/morfologi/meta_derivational/example4_2.mp3"),
        sentence1: "Jenta sitter og smiler.",
        sentence2: "Jenta sitter...",
        answerKey: "(smilende)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 44,
        type: "MetaDerivational",
        orientation: "landscape",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        img: require("@/assets/morfologi/meta_derivational/item1.jpg"),
        audio1: require("@/assets/morfologi/meta_derivational/1_1.mp3"),
        audio2: require("@/assets/morfologi/meta_derivational/1_2.mp3"),
        sentence1: "Katten har mye hår.",
        sentence2: "Katten er veldig...",
        answerKey: "(hårete)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 45,
        type: "MetaDerivational",
        orientation: "landscape",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        img: require("@/assets/morfologi/meta_derivational/item2.jpg"),
        audio1: require("@/assets/morfologi/meta_derivational/2_1.mp3"),
        audio2: require("@/assets/morfologi/meta_derivational/2_2.mp3"),
        sentence1: "Erik trener mye.",
        sentence2: "Erik har vært mye på...",
        answerKey: "(trening)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 46,
        type: "MetaDerivational",
        orientation: "landscape",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        img: require("@/assets/morfologi/meta_derivational/item3.jpg"),
        audio1: require("@/assets/morfologi/meta_derivational/3_1.mp3"),
        audio2: require("@/assets/morfologi/meta_derivational/3_2.mp3"),
        sentence1: "Såpen skummer.",
        sentence2: "Såpen er veldig...",
        answerKey: "(skummete)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 47,
        type: "MetaDerivational",
        orientation: "landscape",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        img: require("@/assets/morfologi/meta_derivational/item4.jpg"),
        audio1: require("@/assets/morfologi/meta_derivational/4_1.mp3"),
        audio2: require("@/assets/morfologi/meta_derivational/4_2.mp3"),
        sentence1: "Mari skriver i timen.",
        sentence2: "Mari har en time med...",
        answerKey: "(skriving)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 48,
        type: "MetaDerivational",
        orientation: "landscape",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        img: require("@/assets/morfologi/meta_derivational/item5.jpg"),
        audio1: require("@/assets/morfologi/meta_derivational/5_1.mp3"),
        audio2: require("@/assets/morfologi/meta_derivational/5_2.mp3"),
        sentence1: "Ole har en genser med striper.",
        sentence2: "Lukas har en genser som er...",
        answerKey: "(stripete)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 49,
        type: "MetaDerivational",
        orientation: "landscape",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        img: require("@/assets/morfologi/meta_derivational/item6.jpg"),
        audio1: require("@/assets/morfologi/meta_derivational/6_1.mp3"),
        audio2: require("@/assets/morfologi/meta_derivational/6_2.mp3"),
        sentence1: "Nicolai beveger seg til musikken",
        sentence2: "Nicolai gjør en...",
        answerKey: "(bevegelse)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 50,
        type: "MetaDerivational",
        orientation: "landscape",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        img: require("@/assets/morfologi/meta_derivational/item7.jpg"),
        audio1: require("@/assets/morfologi/meta_derivational/7_1.mp3"),
        audio2: require("@/assets/morfologi/meta_derivational/7_2.mp3"),
        sentence1: "Anne føler seg trist.",
        sentence2: "Anne har en trist...",
        answerKey: "(følelse)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 51,
        type: "MetaDerivational",
        orientation: "landscape",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        img: require("@/assets/morfologi/meta_derivational/item8.jpg"),
        audio1: require("@/assets/morfologi/meta_derivational/8_1.mp3"),
        audio2: require("@/assets/morfologi/meta_derivational/8_2.mp3"),
        sentence1: "Moren trøster jenta",
        sentence2: "Moren er...",
        answerKey: "(trøstende)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 52,
        type: "MetaDerivational",
        orientation: "landscape",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        img: require("@/assets/morfologi/meta_derivational/item9.jpg"),
        audio1: require("@/assets/morfologi/meta_derivational/9_1.mp3"),
        audio2: require("@/assets/morfologi/meta_derivational/9_2.mp3"),
        sentence1: "Gutten er glad i lesing",
        sentence2: "Gutten liker å...",
        answerKey: "(lese)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 53,
        type: "MetaDerivational",
        orientation: "landscape",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        img: require("@/assets/morfologi/meta_derivational/item10.jpg"),
        audio1: require("@/assets/morfologi/meta_derivational/10_1.mp3"),
        audio2: require("@/assets/morfologi/meta_derivational/10_2.mp3"),
        sentence1: "Han maler veggen",
        sentence2: "Han dekker veggen med...",
        answerKey: "(maling)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 54,
        type: "MetaDerivational",
        orientation: "landscape",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        img: require("@/assets/morfologi/meta_derivational/item11.jpg"),
        audio1: require("@/assets/morfologi/meta_derivational/11_1.mp3"),
        audio2: require("@/assets/morfologi/meta_derivational/11_2.mp3"),
        sentence1: "Han blir sliten av å danse",
        sentence2: "Han synes at å danse er...",
        answerKey: "(slitsomt)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 55,
        type: "MetaDerivational",
        orientation: "landscape",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        img: require("@/assets/morfologi/meta_derivational/item12.jpg"),
        audio1: require("@/assets/morfologi/meta_derivational/12_1.mp3"),
        audio2: require("@/assets/morfologi/meta_derivational/12_2.mp3"),
        sentence1: "Parfymen dufter godt",
        sentence2: "Parfymen er...",
        answerKey: "(duftende)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 56,
        type: "MetaDerivational",
        orientation: "landscape",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        img: require("@/assets/morfologi/meta_derivational/item13.jpg"),
        audio1: require("@/assets/morfologi/meta_derivational/13_1.mp3"),
        audio2: require("@/assets/morfologi/meta_derivational/13_2.mp3"),
        sentence1: "Fuglen flyr",
        sentence2: "Fuglen kommer...",
        answerKey: "(flyvende)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
      {
        id: 57,
        type: "MetaDerivational",
        orientation: "landscape",
        isNarratorInstruction: false,
        instructionAudio: null,
        isPractice: false,
        isScored: true,
        feedbackCorrect: null,
        feedbackWrong: null,
        img: require("@/assets/morfologi/meta_derivational/item14.jpg"),
        audio1: require("@/assets/morfologi/meta_derivational/14_1.mp3"),
        audio2: require("@/assets/morfologi/meta_derivational/14_2.mp3"),
        sentence1: "Jenta fleiper med de andre",
        sentence2: "Jenta er veldig...",
        answerKey: "(fleipete)",
        userAnswer: null,
        nPlaybackTimes: 0,
      },
    ],
  },
  getters: {},
  mutations: {},
  actions: {},
  modules: {},
};
